/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerImigran;
import com.toedter.calendar.JDateChooser;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author RIVANKA
 */
public class Menu extends javax.swing.JFrame {

	/**
	 * Creates new form Menu
	 */
	public Menu() {
		initComponents();
		ctImg = new ControllerImigran(this); //view
		ctImg.isiTable();// perintah untuk mengisi tabel dengan metode controller
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                txtKode = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                txtNama = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                txtWarga = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtAlamat = new javax.swing.JTextArea();
                dateTanggal = new com.toedter.calendar.JDateChooser();
                btnSimpan = new javax.swing.JButton();
                btnUbah = new javax.swing.JButton();
                btnHapus = new javax.swing.JButton();
                btnReset = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                tabelData = new javax.swing.JTable();
                jLabel8 = new javax.swing.JLabel();
                txtCariNama = new javax.swing.JTextField();
                btnCari = new javax.swing.JButton();
                comboJenis = new javax.swing.JComboBox<>();
                jLabel9 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel1.setFont(new java.awt.Font("News706 BT", 0, 18)); // NOI18N
                jLabel1.setText("DATABASE IMIGRASI");
                jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, 41));

                jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel2.setText("Kode Paspor     :");
                jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
                jPanel1.add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 181, -1));

                jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel3.setText("Nama               : ");
                jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
                jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 181, -1));

                jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel4.setText("Alamat              :");
                jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

                jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel5.setText("Warga Negara  :");
                jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));
                jPanel1.add(txtWarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 181, -1));

                jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel6.setText("Jenis kelamin     :");
                jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

                jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel7.setText("Tanggal lahir     :");
                jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

                txtAlamat.setColumns(20);
                txtAlamat.setRows(5);
                jScrollPane1.setViewportView(txtAlamat);

                jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 180, -1));

                dateTanggal.setMaxSelectableDate(new java.util.Date(253370743317000L));
                dateTanggal.setMinSelectableDate(new java.util.Date(-62135791083000L));
                jPanel1.add(dateTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 179, -1));

                btnSimpan.setText("Simpan");
                btnSimpan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSimpanActionPerformed(evt);
                        }
                });
                jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

                btnUbah.setText("Ubah");
                btnUbah.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnUbahActionPerformed(evt);
                        }
                });
                jPanel1.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));

                btnHapus.setText("Hapus");
                btnHapus.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHapusActionPerformed(evt);
                        }
                });
                jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, -1, -1));

                btnReset.setText("Reset");
                btnReset.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnResetActionPerformed(evt);
                        }
                });
                jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

                tabelData.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tabelDataMouseClicked(evt);
                        }
                });
                jScrollPane2.setViewportView(tabelData);

                jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 620, 350));

                jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                jLabel8.setText("Cari Kode / Nama Paspor");
                jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, 20));

                txtCariNama.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtCariNamaActionPerformed(evt);
                        }
                });
                jPanel1.add(txtCariNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 130, 160, -1));

                btnCari.setText("Cari");
                btnCari.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCariActionPerformed(evt);
                        }
                });
                jPanel1.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, -1, -1));

                comboJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));
                comboJenis.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                comboJenisActionPerformed(evt);
                        }
                });
                jPanel1.add(comboJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 179, -1));

                jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\RIVANKA\\Documents\\NetBeansProjects\\Imigrasi\\img\\logo.jpg")); // NOI18N
                jLabel9.setMaximumSize(new java.awt.Dimension(128, 128));
                jLabel9.setMinimumSize(new java.awt.Dimension(128, 128));
                jLabel9.setPreferredSize(new java.awt.Dimension(200, 200));
                jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 80, 70));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void comboJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJenisActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_comboJenisActionPerformed

        private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
            ctImg.insert(); // perintah jika saat meklik button simpan 
	    ctImg.isiTable();// setelah insert otomatis tabel akan terupdate
	    ctImg.reset(); // perintah untuk mengkosongkan kolom input setelah penyimpanan data
        }//GEN-LAST:event_btnSimpanActionPerformed

        private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
            ctImg.update(); // perintah jika saat meklik button ubah
	    ctImg.isiTable();// setelah update otomatis tabel akan terupdate
	    ctImg.reset(); // perintah untuk mengkosongkan kolom input setelah update data
        }//GEN-LAST:event_btnUbahActionPerformed

        private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
             int row = tabelData.getSelectedRow();
		try {
			ctImg.isiField(row);
		} catch (ParseException ex) {
			Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
		}
        }//GEN-LAST:event_tabelDataMouseClicked

        private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
                ctImg.reset(); // perintah untuk mengkosongkan kolom input setelah penyimpanan data
        }//GEN-LAST:event_btnResetActionPerformed

        private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
		ctImg.delete(); // perintah jika saat meklik button ubah
		ctImg.isiTable();// setelah update otomatis tabel akan terupdate
		ctImg.reset(); // perintah untuk mengkosongkan kolom input setelah update data
        }//GEN-LAST:event_btnHapusActionPerformed

        private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
               ctImg.cari();
	       ctImg.reset();
        }//GEN-LAST:event_btnCariActionPerformed

        private void txtCariNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariNamaActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txtCariNamaActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Menu().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCari;
        private javax.swing.JButton btnHapus;
        private javax.swing.JButton btnReset;
        private javax.swing.JButton btnSimpan;
        private javax.swing.JButton btnUbah;
        private javax.swing.JComboBox<String> comboJenis;
        private com.toedter.calendar.JDateChooser dateTanggal;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable tabelData;
        private javax.swing.JTextArea txtAlamat;
        private javax.swing.JTextField txtCariNama;
        private javax.swing.JTextField txtKode;
        private javax.swing.JTextField txtNama;
        private javax.swing.JTextField txtWarga;
        // End of variables declaration//GEN-END:variables
ControllerImigran ctImg;

	public JTable getTableData() { //mengambil JTable dari java swing
		return tabelData;
	} // alasannya karena tabel pada gui Private
	
	
	//berfungsi untuk mengambil data dari field kode karena bersifat private
	public JTextField gettxtKode(){
		return txtKode;
	}
	
	//berfungsi untuk mengambil data dari field Nama karena bersifat private
	public JTextField gettxtNama(){
		return txtNama;
	}
	
	//berfungsi untuk mengambil data dari Text Area alamat karena bersifat private
	public JTextArea gettxtAlamat(){
		return txtAlamat;
	}
	
	//berfungsi untuk mengambil data dari field Warga negara karena bersifat private
	public JTextField gettxtWarga(){
		return txtWarga;
	}
	
	//berfungsi untuk mengambil data dari Combo box jenis kelamin karena bersifat private
	public JComboBox getcomboJenis(){
		return comboJenis;
	}
	
	//berfungsi untuk mengambil data dari dateChooser tanggal lahir karena bersifat private
	public JDateChooser getdateTanggal(){
		return dateTanggal;
	}
	//berfungsi untuk mengambil data dari search karena bersifat private
	public JTextField gettxtCari(){
		return txtCariNama;
	}
}
